name: PhaetonEssentials
main: co.phaeton.trinitek.phaetonessentials.Main
version: 0.5.7
description: Provides custom administrative services and generic commands
author: Trinitek
depend: [PermissionsEx]

commands:
    tpa:
        description: Request to teleport to a player
        usage: "Usage: /<command> <player> [force]"
        permission: phaetonessentials.tp.tpa
        permission-message: You don't have permission to do that!

    tphere:
        description: Request a player teleport to you
        usage: "Usage: /<command> <player> [force]"
        permission: phaetonessentials.tp.tphere
        permission-message: You don't have permission to do that!

    tpaccept:
        description: Accept a teleport request
        usage: "Usage: /<command>"
        permission: phaetonessentials.tp.confirm.accept
        permission-message: You don't have permission to do that!

    tpdeny:
        description: Deny a teleport request
        usage: "Usage: /<command>"
        permission: phaetonessentials.tp.confirm.deny
        permission-message: You don't have permission to do that!
        
    tplist:
        description: List all open teleport requests
        usage: "Usage: /<command>"
        permission: phaetonessentials.tp.list
        permission-message: You don't have permission to do that!
        
    tpcancel:
        description: Cancel a teleport request
        usage: "Usage: /<command>"
        permission: phaetonessentials.tp.cancel
        permission-message: You don't have permission to do that!
        
    back:
        description: Go back to your previous location
        usage: "Usage: /<command> [list] [<pageNumber> [playerName]]"
        permission: phaetonessentials.tp.back
        permission-message: You don't have permission to do that!

    afk:
        description: Toggle your AFK status or list the currently AFK players
        usage: "Usage: /<command> [list]"
        permission: phaetonessentials.afk
        permission-message: You don't have permission to do that!
    testPageBuilder:
        description: Test the PageBuilder class
        usage: "Usage: /<command>"
        permission: phaetonessentials.testPageBuilder
        permission-message: You don't have permission to do that!

permissions:
    phaetonessentials.*:
        description: Gives access to all PhaetonEssentials commands
        children:
            phaetonessentials.tp.tpa: true
            phaetonessentials.tp.tphere: true
            phaetonessentials.tp.list: true
            phaetonessentials.tp.cancel: true
            phaetonessentials.tp.confirm.accept: true
            phaetonessentials.tp.confirm.deny: true
            phaetonessentials.tp.confirm.override: true
            phaetonessentials.tp.back.basic: true
            phaetonessentials.tp.back.specify: true
            phaetonessentials.tp.back.list: true
            phaetonessentials.tp.back.listplayer: true
            phaetonessentials.afk: true
            phaetonessentials.testpagebuilder: true
    phaetonessentials.tp.*:
        description: Gives access to all teleportation commands
        children:
            phaetonessentials.tp.tpa: true
            phaetonessentials.tp.tphere: true
            phaetonessentials.tp.list: true
            phaetonessentials.tp.cancel: true
            phaetonessentials.tp.confirm.accept: true
            phaetonessentials.tp.confirm.deny: true
            phaetonessentials.tp.confirm.override: true
            phaetonessentials.tp.back.basic: true
            phaetonessentials.tp.back.specify: true
            phaetonessentials.tp.back.list: true
            phaetonessentials.tp.back.listplayer: true
    phaetonessentials.tp.confirm.*:
        description: Gives access to all request and deny commands and override flags
        children:
            phaetonessentials.tp.confirm.accept: true
            phaetonessentials.tp.confirm.deny: true
            phaetonessentials.tp.confirm.override: true
    phaetonessentials.tp.back.*:
        description: Gives access to all back-teleporting commands
        children:
            phaetonessentials.tp.back.basic: true
            phaetonessentials.tp.back.specify: true
            phaetonessentials.tp.back.list: true
            phaetonessentials.tp.back.listplayer: true
    phaetonessentials.tp.tpa:
        description: Allows you to request to teleport to another player
        default: true
    phaetonessentials.tp.tphere:
        description: Allows you to request another player to teleport to you
        default: true
    phaetonessentials.tp.list:
        description: Allows you to list all open teleport requests
        default: true
    phaetonessentials.tp.cancel:
        description: Allows you to cancel a teleport request
        default: true
    phaetonessentials.tp.confirm.accept:
        description: Allows you to accept a teleport request
        default: true
    phaetonessentials.tp.confirm.deny:
        description: Allows you to deny a teleport request
        default: true
    phaetonessentials.tp.confirm.override:
        description: Allows you to override the teleport request prompt
        default: op
    phaetonessentials.tp.back.basic:
        description: Allows you to use the basic command
        default: true
    phaetonessentials.tp.back.specify:
        description: Allows you to specify any previous teleport location to go back to
        default: true
    phaetonessentials.tp.back.list:
        description: Allows you to list all of your previous teleport locations
        default: true
    phaetonessentials.tp.back.listplayer:
        description: Allows you to list all of the previous teleport locations of a specified player
        default: true
    phaetonessentials.afk:
        description: Allows you to toggle your AFK status
        default: true
    phaetonessentials.testpagebuilder:
        description: Allows you to test the PageBuilder class
        default: op
